### ISSUE TITLE
Fix whatever is going wrong with demo playground links

### ISSUE THREAD

**Issue by imbstack** [taskcluster/json-e#109]
As can be seen in https://github.com/taskcluster/json-e/issues/65#issuecomment-309842448

[this](https://imbstack.github.io/json-e/?template=foo%3A%20%7B%24eval%3A%20%27bar%27%7D&context=%7Bbar%3A%20null%7D%0A#playground) should render 

```yaml
template: foo: {$eval: 'bar'}
context: {bar: null}
result: {"foo": null}
```

and [this](https://imbstack.github.io/json-e/?template='tc_%24%7Bname%7D'%3A%20'%24%7Bvalue%7D'%0A&context=name%3A%20foo%0Avalue%3A%20null%0A#playground) should render 

```yaml
template: 'tc_${name}': '${value}'
context: {name: foo, value: null}
result: {"tc_foo": "null"}
```
