### ISSUE TITLE
disallow str(array)

### ISSUE THREAD

**Issue by djmitche** [taskcluster/json-e#180]
The behavior of `str` on an array is not currently defined.  We should either define it and test it thoroughly, or disallow it.  I'd lean toward disallowing it.  (From #155)

**Comment by prachi1210** [comment]
Hi, 
I'd like to work on this issue. From https://github.com/taskcluster/json-e/pull/155 I understand that we want to disallow str(array) from just $eval, is that right?

**Comment by djmitche** [comment]
Also in string interpolation -- for example

```yaml
template: "entries are ${str(entries)}"
context:
  entries: [1, 1, 2, 3, 5, 8]
```
