### ISSUE TITLE
Support for partial evaluation

### ISSUE THREAD

**Issue by jonasfj** [taskcluster/json-e#192]
Imagine an expression like:
```yaml
mytag: {$eval: "y"}
mybool:
  $if: 'x > 5':
  then: true
  else: false
```
it accepts `x` and `y` as parameters...

It should be possible to evaluate this partially... Say I only have `y = 2` then it should partially evaluate to:
```yaml
mytag: 2
mybool:
  $if: 'x > 5':
  then: true
  else: false
```
Arguably I would have to call `render({...}, {y: 2, x: placeholder}` to signal that `x` is exists but should be a placeholder...

**Comment by djmitche** [comment]
I don't like this being the result of a context variable missing -- I think that will be bug-prone and difficult to decipher. Also, what if you had
```yaml
mytag: {$eval: "y"}
mybool:
  foo: bar
  enabled:
    $if: 'x > 5'
    then: true
    else: false
```
and you wanted the entire `mybool` property to go away when `x` is not defined?

How about

```yaml
mytag: {$eval: 'y'}
mybool:
  $if: 'defined("x")'
  then:
    $verbatim:
      foo: bar 
      enabled:
        $if: 'x > 5'
        then: true
        else: false  
```

which is to say, introduce `defined(..)` to check if a context variable or property is defined, and `$verbatim` to skip evaluating a sub-structure.

Hm, that misses the "maybe evaluate, maybe don't".  How about `{$verbatim: .., when: 'defined("x")'}`?

**Comment by djmitche** [comment]
Better example:

```yaml
mytag: {$eval: 'y'}
mybool:
  $if: 'defined("x")'
  then:
    foo: bar                                                                                                                                                                                                                                                  
    enabled:
      $if: 'x > 5'
      then: true
      else: false
  else: 
    $verbatim:
      foo: bar
      enabled:
        $if: 'x > 5'
        then: true
        else: false
```
