### ISSUE TITLE
Invalid date-time can be generated, intermittently

### ISSUE THREAD

**Issue by lissyx** [taskcluster/json-e#200]
STR:
 - be on halloween day off
 - submit taskcluster tasks

Expected:
 Works.

Actual:
 Fails with "InputValidationError"

This is the error:
```
{
  "code": "InputValidationError",
   ...
...
      "created": "2017-11-01T22:00:09",
...
}
```

As you can see, `created`, `deadline` and `expires` are all invalid because they lack the timezone info. It is generated here [https://github.com/mozilla/DeepSpeech/blob/12dee36a43fbbebcccf1a3c2cbc8946c54924f7d/taskcluster/linux-opt-base.tyml#L10-L15]:
```
created: { $fromNow: '0 sec' }
deadline: { $fromNow: '1 day' }
expires:
  $if: 'event.event == "push"'
  then: { $fromNow: '6 months' }
else: { $fromNow: '7 days' }
```

This template is being ingested by JSON-e Python module.

*[edit: removed literal newlines as they are confusing TaskWarrior]*
