### ISSUE TITLE
fromNow() in expressions don't read `now` from current context

### ISSUE THREAD

**Issue by jonasfj** [taskcluster/json-e#210]
Example:
```yml
$let:
  now: '2015-12-04T09:28:41.186Z'
in:
  - $eval: 'fromNow("2 min")'
  - $eval: 'fromNow("2 min", "2015-12-04T09:28:41.186Z")'
```

@imbstack, shouldn't we fix this? instead of making a hack where the fromNow function have access to the initial context we could just call functions such that they have access to the context...

In golang I wrap with `WrapFunction` or `WrapFunctionWithContext` in which case the first argument of the function is the context..

In JS we can call with `context` as the `this` parameter...  In python, maybe we can set a secret attribute on the function to indicate that it wants to be called with context, and make an annotation that sets this secret attribute... We can just set the attribute to a magic object `{}` like we do with `deleteMarker` and rely on reference comparison (that way it's protected and people can only create it through the annotation).
