### ISSUE TITLE
make boolean operators short-circuit

### ISSUE THREAD

**Issue by djmitche** [taskcluster/json-e#244]
Currently,
```yaml
context:
  type: 'abc'
  data:
    a: 20
template:
  $eval: "type == 'xyz' && data.y > 20"
```
will fail because `data.y` is not defined.  In most languages, however, `&&` and `||` "short-circuit" by evaluating the left side first and, if the output is then completely determined (as it is here: false), skipping evaluation of the right side.

This is especially helpful when a template can take a few different kinds of input, distinguished by another context element.  For example, mozilla-taskcluster and taskcluster-github provide `tasks_for` to identify the kind of repository event causing `.taskcluster.yml` to be parsed.  So
```yaml
$if: "tasks_for == 'github-push' && event.ref == 'refs/heads/master'"
```
will not work because `event.ref` is not defined for, for example, pull requests.
