### ISSUE TITLE
Allow some sort of numeric range creation

### ISSUE THREAD

**Issue by jgraham** [taskcluster/json-e#250]
https://github.com/web-platform-tests/wpt/pull/12109/commits/0c152be0c4c4b808ebd91f4abae18c2a0faa896c has a case where `json-e` is used for dividing up tests into chunks.
<details>
<summary>Example:</summary>
<pre>
      $flattenDeep:
        $map: [{name: firefox, channel: nightly}, {name: chrome, channel: dev}]
        each(browser):
          $map:
            - [testharness, 1, 15]
            - [testharness, 2, 15]
            - [testharness, 3, 15]
            - [testharness, 4, 15]
            - [testharness, 5, 15]
            - [testharness, 6, 15]
            - [testharness, 7, 15]
            - [testharness, 8, 15]
            - [testharness, 9, 15]
            - [testharness, 10, 15]
            - [testharness, 11, 15]
            - [testharness, 12, 15]
            - [testharness, 13, 15]
            - [testharness, 14, 15]
            - [testharness, 15, 15]
            - [reftest, 1, 10]
            - [reftest, 2, 10]
            - [reftest, 3, 10]
            - [reftest, 4, 10]
            - [reftest, 5, 10]
            - [reftest, 6, 10]
            - [reftest, 7, 10]
            - [reftest, 8, 10]
            - [reftest, 9, 10]
            - [reftest, 10, 10]
            - [wdspec, 1, 1]
each(chunk):
</pre>
</code>

Ideally that could be rewritten something like
```
      $flattenDeep:  
       $map: [{name: firefox, channel: nightly}, {name: chrome, channel: dev}]
        each(browser):
          $map: [["testharness", 15], ["reftest", 10], ["wdspec", 1]
          each(suite):
            $map: {$eval(range(1, suite[1])}
            each(chunk_num):
             - [suite[0], chunk_num, suite[1]]
```

I'm not wedded to the specific syntax ofc; maybe using `$eval` in that context doesn't work and it makes more sense to have a range operator or something. But something that prevents having to list out each entry in a list of numbers would be a big win.

**Comment by djmitche** [comment]
I agree that this would be convenient!

My concern is that we not add anything that might cause evaluation of untrusted inputs to be more "unsafe".  I realize that we're already at risk of exponential time/space usage via nested maps:

```yaml
$map: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]
each(x):
  $map: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]
  each(x):
    $map: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]
    each(x):
      $map: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]
      each(x):
        $map: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]
        each(x):
          $map: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]
          each(x):
            $map: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]
            each(x):
              $map: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]
              each(x): null
```
will, for example, happily crash a tab in Firefox.  So maybe this is no worse.

@jonasfj I know you gave some thought to sandboxing early in JSON-e's history.  Any thoughts?

https://github.com/gf3/sandbox looks useful for Node, but we've got two other languages to think of too :)
