### ISSUE TITLE
$matchOne, a variant of $match

### ISSUE THREAD

**Issue by djmitche** [taskcluster/json-e#257]
I wanted to do this:

```
priority:                                                                                                                                                                                                                                                     
  $match:
    "tasks_for == 'decision'": low 
    "tasks_for == 'cron'": very-low
    "tasks_for == 'action'": lowest
```
https://hg.mozilla.org/try/rev/d39a2a66e72d

But the result was `{priority: ['low']`}` -- the array is unnecessary and undesired.  But it's there since in principle more than one of the options might have matched.

So, this issue proposes an operator similar to `$match`, but where exactly one option must match or the operator fails; and the result does not have an array.  An example of usage would be changing `$match` to `$matchOnce` in the above and getting the result `{priority: low}`.

**Comment by Callek** [comment]
Slight preference for $matchOne with the added caveat that I want it deterministic so I feel if more than one match we should fail out when it's used

**Comment by djmitche** [comment]
Thanks, and agreed regarding determinism!  Which reminds me, #258.

**Comment by owlishDeveloper** [comment]
isn't that a `$switch`?

**Comment by djmitche** [comment]
That is probably a better name :)

**Comment by olsenme** [comment]
I'd like to work on this issue

**Comment by owlishDeveloper** [comment]
@olsenme  have you sent me the screenshots?

**Comment by stuartelimu** [comment]
Can I work on this issue?

**Comment by owlishDeveloper** [comment]
@stuartelimu it's all yours!

**Comment by stuartelimu** [comment]
thank you, on it now

**Comment by stuartelimu** [comment]
thank you so much

**Comment by richardgreg** [comment]
@stuartelimu are you still working on this issue?

**Comment by stuartelimu** [comment]
Yes, I submitted a draft PR.  @owlishDeveloper is reviewing it

**Comment by owlishDeveloper** [comment]
an update: this issue is still open and relevant.

**Comment by noahlaux** [comment]
alternatively you could use a merge to achieve the same thing

```yaml
priority:
  $merge:                                                                                                                                                                                                                                                     
    $match:
      "tasks_for == 'decision'": low 
      "tasks_for == 'cron'": very-low
      "tasks_for == 'action'": lowest
```

**Comment by djmitche** [comment]
That's true!  But @Callek's point about determinism is a good one.  It'd be tempting to write things like 
```
priority:
  $merge:                                                                                                                                                                                                                                                     
    $match:
      'x == 10': ten 
      'x > 5': five
      'x <= 5': small
```
on the assumption that the arms of the match are evaluated in order.  But they aren't.  I think $match is deterministic about the order (worth checking!) but that order may not be what the user expects.

**Comment by djmitche** [comment]
Also, $merge only allows objects, so `low`, `very-low`, etc. wouldn't be allowed.

**Comment by noahlaux** [comment]
Yes I agree with your point! In this case I think, as previously suggested, `$switch` is a better option.

**Comment by djmitche** [comment]
Any chance you want to implement it? :)

**Comment by noahlaux** [comment]
Ooops sorry @djmitche I didn't see this before now :( 

So I looked briefly into the code base and wanted to start by defining the specifications. I more or less took the `$match` operator and justified it, but I had to take some maybe controversial decisions, mainly that no matches does exclude the keys completely in objects and arrays in opposition to return `null`. I think it makes sense so it operators more like an `$if`.

Alternatively one could opt for a normal switch/case interface where you'd provide a single value and have the cases as keys, but I think it provides less value and flexibility.

How do ya'll feel about this guy:

```yaml
---
section: $switch operator
---
title:    $switch, 2 matches, pick first
context:  {cond: 3}
template: {$switch: {'cond == 3': 2, 'cond == 5': 3, 'cond < 5 && cond > 0': 4, 'true': 17}}
result: 2
---
title:    $switch, no matches
context:  {cond: 3}
template: {$switch: {'cond > 5': 2, 'cond == 5': 3, 'cond == 4 || cond < 1': 4}}
result:   null
---
title:    $switch, 1 match in array
context:  {cond: 3}
template: [0, $switch: {'cond == 3': 2, 'cond == 5': 3}]
result:   [0, 2]
---
title:    $switch, 0 matches in array
context:  {cond: 3}
template: [0, $switch: {'cond > 3': 2, 'cond == 5': 3}]
result:   [0]
---
title:    $switch, 1 match in object
context:  {cond: 3}
template: {key: 0, banana: {$switch: {'cond == 3': 2, 'cond == 5': 3}}}
result:   {key: 0, banana: 2}
---
title:    $switch, 0 matches in object
context:  {cond: 3}
template: {key: 0, banana: {$switch: {'cond > 3': 2, 'cond == 5': 3}}}
result:   {key: 0}
---
title:    $switch, is not an object
context:  {cond: 3}
template: {$switch: [{'cond < 5 && cond > 0': 2}]}
error:    'TemplateError: $switch can evaluate objects only'
---
title:    $switch, value that also needs evaluation
context:  {cond: 3, ifcond: false}
template: {$switch: {'cond == 3': {$if: 'ifcond', then: "t", else: "f"}}}
result:   ["f"]
```

**Comment by djmitche** [comment]
Nice!  Starting with specs is the way to go.  This looks good!  Just one issue: ".., pick first' is going to be problematic, since order of object keys is not defined in general, so there's no notion of "first".  In order to avoid ambiguity, I think we need to fail with an error in cases where multiple options evaluate to something truthy.

**Comment by noahlaux** [comment]
hmm, ok, I made an implementation already and it's a-ok for python and JS, but go is not loving me in terms of object keys as you mention

It goes like this for the first test:

```
map[cond < 5 && cond > 0:4 cond == 3:2 cond == 5:3 true:17]
```

```
--- FAIL: TestSpec/$switch_operator (0.01s)
        --- FAIL: TestSpec/$switch_operator/$switch,_2_matches,_pick_first (0.00s)
            jsone_test.go:45: 
                	Error Trace:	jsone_test.go:45
                	Error:      	Not equal: 
                	            	expected: 2
                	            	actual  : 4
                	Test:       	TestSpec/$switch_operator/$switch,_2_matches,_pick_first
                	Messages:   	expected a different result
```

Now my GO skills are not completely stellar, but isn't there a way to get the keys on order in GO. I know maps are unordered, but maybe in another way?

**Comment by noahlaux** [comment]
or maybe you're right, we should fail 🤔

**Comment by djmitche** [comment]
One of the features I like about Go (and Rust, too) is that it actually randomizes order of maps differently on each run.  That helps ensure you don't make mistakes like assuming the ordering is one way or another :)

**Comment by noahlaux** [comment]
Aight, I'll make it to fail in case of multiple matches

**Comment by noahlaux** [comment]
after some sleep though 💤, DK is approaching midnight

**Comment by djmitche** [comment]
:wave: one of the original authors (Jonas) is in DK :)

**Comment by noahlaux** [comment]
ah nice!

I couldn't sleep just yet, so prepared a little. Will clean up tomorrow an make a proper PR https://github.com/taskcluster/json-e/compare/master...noahlaux:feature-switch?expand=1

**Comment by noahlaux** [comment]
Well, it seems like Santa came early, and we have a switch🎅 Maybe this issue should be closed?

**Comment by djmitche** [comment]
Indeed!

Thank you for your work on this!  Since you are actively using JSON-e outside of Taskcluster, it would be great to have you watch the repo and offer your perspective on issues (and of course make PRs where you feel that's useful to you!).  It's difficult to build a "general" tool like JSON-e that is used for a specific purpose within an organization, without making the tool too purpose-specific.  For example, we considered putting a `slugid` built-in into the language.  Having someone to say "uh, that's not useful to us" is a helpful data-point in such conversations.

**Comment by noahlaux** [comment]
Wow that'd be an honor and I'd love to as I have many ideas how to improve! 

I initially stumbled upon JSON-e after I made my own attempt with almost identical approach and syntax, composing data from the outside and in. I went through the interwebs and found quite a few, with interesting approaches, but not really matching my criteria. I wanted it to be powerful (with generators, logic etc), but also very easy to use (declarative) and pretty like python and supported in multiple languages with the ability to extend the vocabolary and 
using just YAML with no special markup (although [ytt](https://get-ytt.io/)'s ways of solving some things are quite awesome).

I am using it in combination with [reactivex](http://reactivex.io/) which powers a general purpose reative streams solution with observers and effects, and I freaking love it (soon to be open sourced). I was able to cook down 1000 of lines of proprietary code down to (to me) beautiful and easy to understand "recipe" for an IOT solution I'm working on. It's not quite done yet, but it's approaching something useful.

In this example I'm connecting through a socket and continously recieving messages, which in return scouts devices (seats) from raw data, categorizing people and objects (writing to database) and finally does a passenger count.

As you can see JSON-e has a big role in this, but I also have custom tokens (such as `socket`, `set`), and I love the readibility, and even through it's not a language per say, there's enough mojo so I can keep DRY. I simple run this with my engine and magic starts to happen.

```yaml
run:
  name: Scout seats from MCU

  when:
    # connect to MCU
    socket:
      host: ${env.CONSUMER_HOST}
      contentType: json
      port: ${env.CONSUMER_PORT}

  then:
    $if: data.ObjectType == 'receivedPayload'
    then:
      scout:
        $map:
          # top and bottom is the bit slot range for the sensors in the payload
          - name: ${data.nodeId} - seat 1
            top: [1, 5]
            bottom: [5, 9]
          - name: ${data.nodeId} - seat 2
            top: [9, 13]
            bottom: [13, 18]
            
        each(seat):
          $merge:
            - type: seat
              name: ${seat.name}
              timestamp: 
                $eval: data.timestamp - (data.packageAgeMicroSecs * 1000)

            - $switch:
                # system information
                "data.payload[0] == 200":
                  batteryLevel:
                    $eval: data.payload[1] / 10
                # node type 4
                "data.payload[0] == 4":
                  cushionTopCapacitance:
                    $eval: readIntLE(data.payload[seat.top[0]:seat.top[1]])
                  cushionBottomCapacitance:
                    $eval: readIntLE(data.payload[seat.bottom[0]:seat.bottom[1]])

---
run:
  name: Seat categorization

  when:
    observe:
      type: seat
      cushionTopCapacitance: 
      cushionBottomCapacitance:

  then:
    set:
      id: ${data.id}
      cushionCategory:
        $let:
          difference: data.cushionTopCapacitance - data.cushionBottomCapacitance
        in:
          $switch:
            "inRange(difference, 180, 2000)": empty
            "inRange(difference, 2343, 6000)": bag
            "inRange(difference, 12500, 25000)": person

---
run:
  name: Passenger count

  when:
    observe:
      type: seat
      cushionCategory: 
        $includes: [empty, bag, person]

  then:
    set:
      type: coach
      passengersSitting:
        $let:
          current: data.cushionCategory
          former: formerData.cushionCategory
        in:
          $switch:
            "former == 'empty' && current in ['person', 'bag']":
              $eval: self.passengersSitting + 1
            "former in ['person', 'bag'] && current == 'empty'":
              $eval: self.passengersSitting - 1
  ```
