### ISSUE TITLE
Allow using variables defined above in same $let

### ISSUE THREAD

**Issue by mitchhentges** [taskcluster/json-e#263]
I have some values that I calculated in advance for my task definition. Some of these values depend on each other. For example, right now, I have:

```
$let:
  # <snip>
  repository: ${event.repository.clone_url}
  is_mozilla_mobile_repo: 
    $eval: event.repository.clone_url == 'https://github.com/mozilla-mobile/reference-browser'
  command_staging_flag:
    $if: event.repository.clone_url == 'https://github.com/mozilla-mobile/reference-browser'
    then: ''
    else: '--staging'
in:
  # uses repository, is_mozilla_mobile_repo, command_staging_flag
```

I'd love to be able to use items defined in the `$let` to be used in the values produced below. If this were the case, I could simplify the above to:

```
$let:
  # <snip>
  repository: ${event.repository.clone_url}
  is_mozilla_mobile_repo: 
    $eval: repository == https://github.com/mozilla-mobile/reference-browser'
  command_staging_flag:
    $if: is_mozilla_mobile_repo
    then: ''
    else: '--staging'
in:
  # uses repository, is_mozilla_mobile_repo, command_staging_flag
```

**Comment by djmitche** [comment]
The downside is, order isn't defined in a JSON object, so the notion of "above" is a purely textual one that is not represented in the data structures on which json-e operates.

We could possibly offer a more complex syntax that uses an array to enforce some ordering.. maybe something like

```yaml
$let:
  # <snip>
  - repository: ${event.repository.clone_url}
  - is_mozilla_mobile_repo: 
      $eval: repository == https://github.com/mozilla-mobile/reference-browser'
  - command_staging_flag:
      $if: is_mozilla_mobile_repo
      then: ''
      else: '--staging'
in: ...
```

If we did that, I think we'd want to enforce that each array item is a single-property object (or single-key dictionary in Python terms).

What do you think?  Is that syntax readable? Writable?  Too easy to get wrong?
