### ISSUE TITLE
Error message has incorrect JSON path

### ISSUE THREAD

**Issue by djmitche** [taskcluster/json-e#276]
template:
```yaml
tasks:
  $flattenDeep:
  - {$if: tasks_for == "github-push"}
  - {$if: tasks_for == "github-pull-request"}
  - $map:
    - {}
    each(operation):
    - {$if: event.action}
```
context:
```yaml
tasks_for: "foo"
event: {}
```
result:
```
TemplateError at template.tasks[2][0]: action not found in {}
```

*Expected*: `TemplateError at template.tasks.$flattenDeep[2]['each(operation)'][0].$if: ..`

So the path within the JSON is not correct..
