### ISSUE TITLE
defined behaves differently in different implementations

### ISSUE THREAD

**Issue by djmitche** [taskcluster/json-e#342]
The following test case:
```yaml
---
title: 'defined with empty variable from a let expression'
context: {}
template: {$let: {var: 10}, in: {$if: "defined('var')", then: 't', else: 'f'}}
result: t
```
fails on JS and Python, but succeeds on Golang.  The test case demonstrates the expected behavior, though: a variable defined with `$let` should be visible to `defined`. I think the issue is that in the JS and Python implementations, the `context` variable that is being referred to in the implementation of `defined` is the original, top-level `context` to which the builtins were added, rather than the `context` that's active at the time the expression is evaluated.

Since this behavior differs between implementations, it will be important to fix this before we make another release.

@Nicrii is there any chance you could have a look?
