### ISSUE TITLE
New feature: `join`

### ISSUE THREAD

**Issue by noahlaux** [taskcluster/json-e#370]
A list `join` functionality (together with #369 `split`) will give superpowers when composing with lists.

## Usage

```yaml
context:
suspects
  - foo
  - bar
  - baz
template: ${join(suspects, ' ')}
result: foo bar baz
```

## Specification

```yaml
title: join with string separator
context: {}
template: {$eval: "join(['join', 'me'], ' ')"}
result: "join me"
---
title: join with same
context: {}
template: {$eval: "join([',', ','], ',')"}
result: ",,,"
---
title: join with number separator
context: {}
template: {$eval: "join([1, 3], 2)"}
result: "123"
---
title: join with string
context: {}
template: {$eval: "join('cannot join string')"}
error: "BuiltinError: invalid arguments to builtin: join"
---
title: join with object
context: {}
template: {$eval: "join({})"}
error: "BuiltinError: invalid arguments to builtin: join"
---
title: join with boolean
context: {}
template: {$eval: "join(false)"}
error: "BuiltinError: invalid arguments to builtin: join"
---
```
