### ISSUE TITLE
Need object literal support in expression language

### ISSUE THREAD

**Issue by djmitche** [taskcluster/json-e#47]
So we can do something like `{$eval: "{a: x+10, b: x+20}"}`.

@jonasfj I'm not totally convinced we need this.  The above example could be written `{a: {$eval: "x+10"}, b: {$eval: "x+20"}}`.  Is this *never* necessary?

**Comment by jonasfj** [comment]
I don't think it's _necessary_, but it might be super convenient in many cases.

For example passing an object to a function as arguments:
```
$eval: "customFunction({name: username, smart: username == 'jonasfj'})"
```
with a context like:
```js
{
  username: 'jonasfj',
  customFunction: function(options) {...},
}
```
You can do this using the `$let` construct, but it'll be super clumsy and hard to read.

Inline objects are useful for passing arguments, and many other things...

**Comment by djmitche** [comment]
Hm, but there are tests like
```yaml
title: 'parse object (10)'
context: {key: 1}
template: {$eval: '{a: key, "b": min(key + 1, 1)}'}
result: {a: 1, b: 1}
```
so I guess this is already supported!  I missed that in the source, somehow.  I'll document it.
