### ISSUE TITLE
document that numbers, booleans, and nulls can be interpolated

### ISSUE THREAD

**Issue by djmitche** [taskcluster/json-e#65]
These values interpolate as their JSON literal values (numbers are numbers, `true` and `false` in lowercase, and `null`).

<strike>Note that `null` does not currently interpolate, so that will need to be fixed too.</strike>

**Comment by imbstack** [comment]
I'm trying to understand what we mean here. Do we mean interpolate like [this](https://imbstack.github.io/json-e/?template=foo%3A%20%7B%24eval%3A%20'bar'%7D&context=%7Bbar%3A%20null%7D%0A#playground) or does it have to be like [this](https://imbstack.github.io/json-e/?template='tc_%24%7Bname%7D'%3A%20'%24%7Bvalue%7D'%0A&context=name%3A%20foo%0Avalue%3A%20null%0A#playground)?

**Comment by djmitche** [comment]
Sorry, I meant example 2.

```yaml
template:
  - "number: ${num}"
  - "booleans: ${t} ${f}"
  - "null: ${nil}"
context:
  number: 3
  t: true
  f: false
  nil: null
result:
 - "number: 3"
 - "booleans: true false"
 - "null: null"
```
The last sentence in the first comment ("Note that null does not currently interpolate, so that will need to be fixed too") was wrong and has anyway now been fixed.
